# Generated by Django 5.0.1 on 2024-01-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='username', max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=64)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('_id', models.CharField(db_column='url_id', max_length=8, primary_key=True, serialize=False)),
                ('target', models.CharField(db_column='target_url', max_length=512)),
                ('expiration', models.BigIntegerField(db_column='expiration_date')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='url_shortener.user')),
            ],
            options={
                'db_table': 'url',
            },
        ),
    ]
