version: "3"
services:
  app:
    container_name: "app"
    build: ./app/
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "psqldb"
      DB_PORT: 5432
      DB_USER: "admin"
      DB_PASSWORD: "passwd"
      DB_DEFAULT_DB_NAME: "url_shortener"
      SECRET_KEY: "should-not-be-visible-4b_$$ti-gecxp#4eqfn@5p1pjge^#!a69*x85o9j8-+h4=3yo!8"
    depends_on:
      - db
    restart: always
  
  db:
    container_name: psqldb
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "url_shortener"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always